[package]
name = "ttree-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow      = { workspace = true }
crossterm   = { workspace = true }
directories = { workspace = true }
ratatui     = { workspace = true }
tokio       = { workspace = true }
vt100       = { workspace = true }
