[package]
name = "ttree"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui        = "0.30.0"
crossterm      = "0.28"
tokio          = { version = "1", features = ["full"] }
indexmap       = "2"
anyhow         = "1"
clap           = { version = "4", features = ["derive"] }
serde          = { version = "1", features = ["derive"] }
toml           = "0.8"
fuzzy-matcher  = "0.3"
directories    = "5"
tui-term       = "0.3.4"
vt100          = "0.16.2"
portable-pty   = "0.8.1"
